; App PHP overrides
memory_limit = 256M
upload_max_filesize = 20M
post_max_size = 25M
max_execution_time = 60
date.timezone = Europe/Paris
realpath_cache_size = 4096K
realpath_cache_ttl = 600

; OPcache
opcache.enable = 1
opcache.memory_consumption = 256
opcache.max_accelerated_files = 20000
opcache.validate_timestamps = 1
opcache.revalidate_freq = 0

; APCu
apc.enable_cli = 1
