twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        menu_service: '@App\Service\MenuService'
        widget_service: '@App\Service\WidgetService'

when@test:
    twig:
        strict_variables: true
